### ISSUE TITLE
Help please extension installation problem

### ISSUE THREAD

**Issue by chrishat34** [ciuffetelli/driver-practical-test-dvsa#1]
Hi, just tried to install the extension but i cannot seem to enable it. chrome seems to block it. i am in developer mode - any advice would be brilliant. Thanks

**Comment by chrishat34** [comment]
![Screenshot](https://user-images.githubusercontent.com/43535243/235219673-8692e31a-fc82-49ee-a3f8-7d134a9ac9d6.png)

**Comment by ciuffetelli** [comment]
When you add an extension pack locally that doesn't go through the
 Chrome Store, you will see this message.

You can use the official Chrome Store package.

https://chrome.google.com/webstore/detail/uk-drive-practical-test-b/emnhllljokeicdcnjccdagoddjlimilh
